---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include = FALSE}
library(tidyverse)
library(httr)
library(jsonlite)
library(plotly)
library(flexdashboard)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r get data, include = F}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows()
```

```{r sample}
set.seed(6)
sample_df = 
  nyc_inspections %>% 
  sample_n(10000)
```

```{r tidy sample_df}
sample_df = 
  sample_df %>% 
  mutate(
    borough = as.factor(boro),
    critical_flag = as.factor(critical_flag),
    grade = as.factor(grade),
    score = as.double(score),
    grade_date = as.Date(grade_date)) %>% 
    select(dba, borough, cuisine_description, critical_flag, score, grade, grade_date) %>% 
    filter(grade == c("A", "B", "C"))
```

Column {data-width=650}
-----------------------------------------------------------------------

## Plot 1

```{r chinese food plot, message = F, warning = F}
sample_df %>% 
  filter(str_detect(cuisine_description, "[Cc][Hh][Ii][Nn][Ee][Ss][Ee]")) %>% 
  group_by(borough, grade) %>% 
  count(grade) %>% 
  plot_ly(x = ~grade, y = ~n, color = ~borough, type = "bar", colors = "viridis") %>% 
  layout(title = "Distribution of Chinese-Food Inspection Grades", xaxis = list(title = "Grade"), yaxis = list(title = "Count"))
```

Column {data-width=350}
-----------------------------------------------------------------------

## Plot 2

```{r mean score vs borough plot, message = F, warning = F}
sample_df %>% 
  group_by(borough, score) %>% 
  summarize(mean_score = mean(score)) %>% 
  plot_ly(x = ~borough, y = ~mean_score, type = "box", color = ~borough, colors = "viridis") %>% 
  layout(title = "Mean Inspection Scores for All Restauarnt Types", xaxis = list(title = "Borough"), yaxis = list(title = "Mean Score"))
```

## Plot 3

```{r Mexican food score over time plot, message = F, warning = F}
sample_df %>%
  filter(str_detect(cuisine_description, "[Mm][Ee][Xx][Ii][Cc][Aa][Nn]")) %>% 
  plot_ly(x = ~grade_date, y = ~score, type = "scatter") %>% 
  layout(title = "Inspection Scores for Mexican-Food Restaurants Over Time", xaxis = list(title = "Borough"), yaxis = list(title = "Score"))
```
