---
title: "Resume ([click here](resume.pdf) to download)"
output: 
  html_document:
    toc: true
    toc_float: true
---
***

<div align = "center">
## **David Nemirovsky**

**Brooklyn, New York 11234 | 1-(347)-394-9939 | david.nemirovsky97@gmail.com | [davidnemirovsky.com](davidnemirovsky.com)**

***

<div align = "left">
### **Education**

##### **Columbia University Mailman School of Public Health**, New York, NY (May 2022)

Master of Science in Biostatistics GPA: 3.71

Relevant Coursework: Biostatistics I & II (GLM & Longitudinal Data Analysis), Data Science I & II (Machine Learning Algorithms), Clinical Trial Methodology, Survival Analysis, Latent Variables and Structural Equation Modeling, Statistical Inference (Classical & Bayesian Estimation)

Involvement: Biostatistics Computing Club, Healthcare Data Analytics

**Honors:** FORWARD (Fighting Oppression, Racism & White Supremacy Through Action, Research & Discourse) Community Fellowship Award

##### **Hunter College**, New York, NY (May 2019)

Bachelor of Arts in Statistics, Bachelor of Arts in Biochemistry GPA: 3.71 (Statistics GPA: 3.97)

**Honors:** Departmental Honors in Biochemistry, Yalow Honors Scholar, Dean’s List, Shirley Kurmin Mazur Award in Mathematics

***

### **Work Experience**

#### **Memorial Sloan Kettering Cancer Center, Department of Epidemiology and Biostatistics**, New York, NY (May 2022 - Present)

*Assistant Research Biostatistician*

#### **Columbia University Mailman School of Public Health, Department of Population & Family Health**, New York, NY (June 2021 – May 2022)

*Quantitative Research Assistant*

+ Developed statistical models to examine significance of multiracial identification across 8 health outcomes and 4 covariates using R
+ Constructed dozens of exploratory plots/tables to visualize differences among multiracial groups using `ggplot` and `Shiny` packages in R
+ Generated accessible reports of statistical findings for discussions with team and principal investigator using RMarkdown
+ Tidied dataset containing over 3000 participants and 175 variables into workable dataset using R

#### **Columbia University Irving Medical Center, Department of Neurology**, New York, NY (June 2021 – May 2022)

*Research Fellow*

+ Analyzed dataset of 75 underserved 5th grade students to evaluate social and emotional learning (SEL) interventions using R
+	Established novel data infrastructure for efficient assessment of intervention efficacy during implementation of SEL modules using SQL
+	Finalized study design and compose IRB protocol for pilot clinical trial with vulnerable population
+	Conducted in-depth research review on hundreds of SEL measurement scales to be optimally used in gauging mental health improvement

##### **Department of Chemistry at Hunter College**, New York, NY (January 2020 – May 2022)

*Adjunct Lecturer for General Chemistry Lab and Inquiries into the Nature of Matter*

+	Instructed 60+ undergraduate students on proper lab techniques, safety protocol, and fundamental concepts of chemistry within experiments 
+	Assigned grades based on performance in laboratory and lab reports, as well as host weekly office hours to provide additional instruction 

##### **Private Tutor**, New York, NY (August 2019 – May 2022)

*Subjects: Algebra, Trigonometry, Calculus, Statistics, Biology, Chemistry (All Middle School – College Level)*

+ Prepared lesson plans tailored to needs of specific students and engage them using applicable examples and vernacular
+	Assisted with assigned homework and projects, with recent clients receiving high marks on the math section of the SAT and As in Calculus

##### **Watch Limit**, New York, NY	(November 2019 – June 2021)

*Operations Manager*

+	Examined monthly sales data to discover trends and set inventory prices based on current market value using R 
+	Input and managed business inventory between $1-2 million via MS Excel 
+	Oversaw and updated website on rolling basis to accurately reflect market changes

##### **Public School Athletic League**, New York, NY (January 2016 – Present)

*Wrestling Tournament Manager*

+	Generate tournament brackets, minimizing variability in matches per mat and average time between matches
+	Rectify spreadsheets with hundreds of registered wrestlers prior to tournament’s start
+	Dictate assembly of electronics and equipment needed for tournament’s operation

##### **Nadine Johnson & Associates, Inc.**, New York, NY (January 2016 – January 2020)

*Assistant Finance Director*

+	Determined company’s monthly profitability by comparing revenue versus taxes and expenses using MS Excel
+	Reconcile bank statements up to $250,000 monthly, ensuring accurate bookkeeping and constructed invoices by organizing client and employee expenses

***

### **Skills**

##### **Language:**Intermediate Russian

##### **Software:** R, SAS, SQL, SPSS, Access, and Excel (All advanced usage)